### ISSUE TITLE
Image-based map loading

### ISSUE THREAD

**Issue by KSXGroup** [NVlabs/trajdata#18]
Datasets like ETH/UCY use image based map. It seems that map api does not provide image based loading, any solution?

**Comment by KSXGroup** [comment]
I found there is a related question https://github.com/StanfordASL/Trajectron-plus-plus/issues/14 
Is there any plan to integrate this into trajdata?

One more question is in your paper "Expanding the Deployment Envelope of Behavior Prediction via Adaptive Meta-Learning", you mentioned you are using maps in ETH/UCY. Is the adaption result reported in paper based on both trajectory and local map patch for ETH/UCY ? 

Thanks!

**Comment by BorisIvanovic** [comment]
HI @KSXGroup , thank you for your questions!

At this time I don't have any plans for how to integrate image-based maps into trajdata, especially since I believe it would require manually annotating images to determine walkable regions and other semantic areas...

Regarding your second question:
> Is the adaption result reported in paper based on both trajectory and local map patch for ETH/UCY ?

ETH/UCY do not have any maps in trajdata, and so the adaption results reported in the "Expanding the Deployment Envelope of Behavior Prediction via Adaptive Meta-Learning" paper for ETH/UCY are only based on trajectory information.
